### ISSUE TITLE
Evitar sincronización de temporales LaTeX

### ISSUE THREAD

**Issue by alvarag** [JornezMM/PDAIvolution#1]
Como hemos hablado, LaTeX genera muchos ficheros temporales, para evitar que estos se suban a Github lo mejor es crear un ".gitignore" del estilo a https://github.com/github/gitignore/blob/main/TeX.gitignore.

Comentarios a la memoria:
[memoria-3.pdf](https://github.com/JornezMM/tfg/files/13204302/memoria-3.pdf)

**Comment by JornezMM** [comment]
Ya he añadido el .gitignore y he eliminado los archivos temporal. En el archivo que has enviado no encuentro los comentarios.

**Comment by alvarag** [comment]
Disculpa, subí la que no era...
[memoria-AAG.pdf](https://github.com/JornezMM/tfg/files/13216258/memoria-AAG.pdf)
