### ISSUE TITLE
Conceptos teóricos E.T. 2h

### ISSUE THREAD

**Issue by JornezMM** [JornezMM/PDAIvolution#6]
Continuar con la documentación de los conceptos teóricos

**Comment by alvarag** [comment]
Comentarios sobre memoria

[memoria-AAG.pdf](https://github.com/JornezMM/tfg/files/15090646/memoria-AAG.pdf)

**Comment by alvarag** [comment]
Comentarios sobre anexos

[anexos-AAG.pdf](https://github.com/JornezMM/tfg/files/15385988/anexos-AAG.pdf)

**Comment by alvarag** [comment]
Comentarios en memoria y anexos

[anexos-AAG.pdf](https://github.com/user-attachments/files/15803187/anexos-AAG.pdf)
[memoria-AAG.pdf](https://github.com/user-attachments/files/15803193/memoria-AAG.pdf)

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos: vigila las tildes ;)

[anexos-AAG.pdf](https://github.com/user-attachments/files/15967523/anexos-AAG.pdf)
[memoria-AAG.pdf](https://github.com/user-attachments/files/15967525/memoria-AAG.pdf)

**Comment by alvarag** [comment]
Comentarios sobre memoria: ojo a las tildes que te las comes todas!!

[memoria-5.pdf](https://github.com/user-attachments/files/16094857/memoria-5.pdf)

**Comment by alvarag** [comment]
Comentarios finales
[anexos-AAG.pdf](https://github.com/user-attachments/files/16123846/anexos-AAG.pdf)
